name: Git command

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run git command for unshallowing
      run: git fetch --shallow-since="1 month ago" --update-shallow --refetch
    - name: Run git rev-list
      run: git rev-list --objects --no-object-names --filter=blob:none --since="1 month ago" HEAD
